theme: minima

collections:
  projects:
    output: true
  microProjects:
    output: true
  moscowProjects:
    output: false

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
    values:
      layout: "default"

exclude:
  - README.md
  - build-scripts
  - Gemfile*
  - toolchain-website*

load_paths:
  - _sass

baseurl: ""
url: https://toolchain-labs.com/
repository: SuduIDE/toolchain-website

plugins:
  - jemoji
